### PR TITLE
Update Log4J to 2.17.1 in all modules, add es-7.16.3 module

### PR DESCRIPTION
**Pull request by Naicisum**
Update Log4J to 2.17.1 in all modules, add es-7.16.3 module

### CODE REVIEW

**Comment by Naicisum** [comment]
> The changes look straightforward. Just one question: Did you already test it with ES 7.16.3?

Yep, already running with it in our production environment.

**Review by swachter — APPROVED** [review]
LGTM

**Comment by RangerRick** [comment]
@swachter do you know what we need to do to make a "release" of this?

**Comment by swachter** [comment]
Unfortunately, not.

**Pull request merged**
